name: Deploy to Docker Hub

on:
  push:
    branches:
      - main # Triggers on push to the main branch

jobs:
  build_and_push_to_dockerhub:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated to v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4 # Updated to v4
        with:
          java-version: '17'
          distribution: 'temurin' # Using Temurin, consistent with Dockerfile

      - name: Cache Maven packages
        uses: actions/cache@v4 # Updated to v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: ./mvnw clean install -B -DskipTests # -B for batch mode, -DskipTests to speed up CI build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Updated to v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3 # Updated to v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5 # Updated to v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/validation-service # Assumes DOCKERHUB_USERNAME is your Docker Hub username and validation-service is the desired image name. Adjust if your repo name is different.
          tags: |
            type=sha,prefix=
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5 # Updated to v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
